title: 'Project Name'
github: 'https://github.com/eddywashere/jekyll-tldr'
baseurl: "/demo"
highlighter: pygments
kramdown:
  toc_levels: "1..3"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
collections:
  docs:
    output: true
    permalink: /docs/:path/
sass:
    sass_dir: _scss
    style: :compressed
